package se.nrm.dina.dnakey.portal.util;

/**
 * Test fast files
 * 
 * @author idali
 */
public class FastaFiles {

  private static final String FASTA_FILE_1 = ">Seq 1\n"
          + "CTTATCTTCGGGGCATGAGCCGGAATAATTGGCACAGCACTCAGCCTACTGATCCGCGCAGAACTAGGCCAACCAGGAACCCTCCTG"
          + "GGCGACGACCAAATTTACAACGTAATCGTCACCGCCCACGCCTTTGTAATAATCTTCTTCATGGTAATACCCATCATGATTGGAGGA"
          + "TTCGGCAACTGATTAGTCCCCCTAATAATCGGCGCCCCTGACATAGCATTCCCACGAATAAACAACATAAGCTTCTGACTCCTCCCA"
          + "CCATCATTCCTCCTCCTACTCGCCTCATCTACCGTAGAAGCTGGGGCCGGTACAGGTTGAACCGTGTACCCACCCCTAGCAGGCAAC"
          + "CTGGCCCACGCCGGAGCCTCAGTAGACCTAGCTATCTTCTCCCTTCACCTAGCCGGTGTCTCCTCCATCCTCGGGGCCATTAACTTC"
          + "ATTACCACAGCCATCAACATAAAACCCCCTGCACTCTCACAGTACCAAACCCCACTTTTCGTCTGATCGGTCCTAATTACCGCCATC"
          + "CTACTCCTCCTATCACTCCCTGTCCTCGCCGCCGGCATCACAATGCTACTAACCGACCGAAACCTAAACACCACATTCTTTGACCCC"
          + "GCCGGAGGAGGAGACCCAATCCTGTACCAACACCTATTT\n\n";

  private static final String FASTA_FILE_2 = ">Seq 2\n"
          + "CTAATCTTCGGTGCATGAGCTGGCATGGTCGGAACCGCCCTCAGCCTGCTTATTCGTGCAGAACTAGGCCAACCAGGAACCCTCTTG"
          + "GGAGATGACCAAATCTACAATGTAATCGTTACTGCTCATGCATTCGTAATAATTTTCTTCATAGTTATACCAATCATGATCGGAGGA"
          + "TTTGGAAATTGACTAGTCCCACTCATAATCGGCGCCCCCGACATAGCATTTCCTCGTATAAACAATATAAGCTTCTGACTACTCCCC"
          + "CCATCATTCCTATTATTACTAGCATCCTCTACAGTAGAAGCTGGAGCTGGCACAGGATGAACAGTATATCCACCCCTCGCCGGCAAC"
          + "CTAGCCCACGCAGGAGCCTCAGTAGACCTAGCTATTTTCTCCCTCCATTTAGCAGGTGTCTCCTCCATCCTAGGTGCCATTAACTTT"
          + "ATCACCACTGCCATTAACATAAAACCACCAGCCCTGTCCCAATACCAAACACCCCTATTTGTATGATCAGTACTCATTACCGCCGTC"
          + "TTACTGCTACTCTCACTCCCAGTCCTTGCTGCCGGCATCACCATGCTATTAACAGATCGTAATCTAAACACCACATTCTTTGACCCA"
          + "GCCGGAGGAGGAGACCCAGTCCTATACCAACATCTCTTC\n\n";

  private static final String FASTA_FILE_3 = ">Seq 3\n"
          + "CTGATTTTCGGCGCATGAGCCGGAATGGTAGGTACCGCCTTAAGCCTCCTCATCCGAGCAGAACTAGGCCAACCCGGAGCCCTCCTG"
          + "GGAGACGACCAAGTCTACAACGTAGTCGTCACAGCCCACGCTTTCGTAATAATCTTCTTCATAGTTATACCAATTATGATCGGAGGG"
          + "TTCGGAAACTGACTCGTCCCCCTAATAATCGGAGCCCCAGACATAGCATTCCCACGGATAAACAACATAAGCTTCTGACTACTCCCC"
          + "CCATCCTTCCTGCTACTACTAGCATCTTCTACTGTAGAAGCAGGCGTAGGAACAGGCTGAACAGTGTACCCCCCACTAGCCGGAAAC"
          + "CTAGCCCATGCCGGAGCTTCGGTCGACCTCGCAATCTTCTCCCTTCACCTAGCCGGTATCTCTTCAATCCTGGGGGCAATCAACTTC"
          + "ATCACTACAGCAATCAACATAAAACCACCTGCCCTCTCACAATACCAAACCCCTCTATTCGTCTGATCAGTCTTAATTACCGCAGTC"
          + "CTCCTGCTCCTGTCCCTCCCAGTCCTTGCCGCCGGCATTACAATACTACTCACGGACCGTAACCTTAACACCACATTCTTCGACCCT"
          + "GCTGGAGGAGGAGACCCCGTCCTATACCAACATCTCTTC\n\n";

  private static final String FASTA_FILE_4 = ">Seq 4\n"
          + "CTACTCTTCGGAGCATGAGCAGGTATAGCCGGTACCGCCCTTAGCCTTCTTATTCGAGCAGAACTTGGCCAACCGGGGACTCTTCTT"
          + "GGAGACGACCAGATCTACAATGTCATCGTCACCGCCCATGCCTTCGTAATAATCTTCTTCATAGTCATACCCATTATAATCGGAGGA"
          + "TTTGGAAACTGACTAGTCCCCCTTATAATTGGAGCCCCAGACATAGCATTCCCCCGAATAAACAACATAAGTTTCTGATTACTCCCC"
          + "CCATCCTTCCTACTACTCCTGGCATCTTCCACAGTAGAAGCCGGAGTCGGAACAGGATGAACCGTTTACCCCCCCTTAGCAGGCAAC"
          + "CTGGCCCATGCTGGCGCCTCAGTAGACCTAGCCATCTTCTCCCTGCACCTCGCAGGTGTATCTTCCATCCTGGGGGCAATCAACTTT"
          + "ATCACAACAGCCATTAACATAAAACCCCCTGCCCTGTCACAATACCAAACCCCATTATTCGTGTGATCCGTACTCATCACAGCCGTA"
          + "CTCCTACTGCTCTCACTCCCAGTCTTAGCCGCTGGCATCACCATACTACTAACCGACCGAAATCTAAACACCACATTCTTCGACCCC"
          + "GCCGGAGGAGGAGACCCTATTCTCTACCAACACCTATTC\n\n";

  private static final String FASTA_FILE_5 = ">Seq 5\n"
          + "CTAGTCTTCGGTGCATGGGCCGGCATAGTAGGCACAGCCCTCAGCCTCCTAATTCGGGCAGAACTAGGACAACCAGGAACCCTTCTA"
          + "GGGGACGACCAGATTTACAACGTAATTGTCACTGCCCACGCCTTTGTAATAATTTTCTTCATGGTAATACCCATCATGATTGGCGGA"
          + "TTTGGAAACTGACTAGTCCCCCTCATAATCGGAGCCCCGGACATAGCATTTCCCCGCATAAATAACATAAGCTTCTGACTACTTCCC"
          + "CCCTCCTTCCTATTACTGCTAGCATCTTCCACAGTTGAAGCTGGAGCAGGCACAGGATGGACTGTCTACCCACCACTGGCCAGCAAC"
          + "ATAGCCCACGCCGGGGCCTCAGTTGATCTGGCCATTTTTTCGCTCCACTTAGCAGGTATCTCATCAATCCTCGGGGCAATCAACTTC"
          + "ATTACAACCGCCATCAACATAAAACCCCCGGCCCTGTCACAATACCAAACACCCCTATTTGTATGATCAGTCTTCATCACCGCAATC"
          + "CTACTTCTGCTATCCCTCCCAGTACTAGCCGCTGGCATTACCATGCTCCTAACTGACCGAAACCTAAACACCACATTCTTTGATCCT"
          + "GCCGGAGGGGGCGACCCTGTCCTGTACCAGCACCTTTTC\n\n";

  private static final String FASTA_FILE_6 = ">Seq 6\n"
          + "TCACCCATCGCCAGATAGATTGCGCTGGCACCGCAGATCAGACCAATCCAGCCGGCAAAGTGGATGATTGCGGCGTTACC"
          + "GGCAATGTTACCGATCGCCAGCAGGGCAAACAGCACGGTCAGGCTAAAGAAAACGAATTGCAGAACGCGTGCGCCTTTCA"
          + "GCGTGCCGAAGAACATAAACAGCGTAAATACGCCCCACAGACCCAGGTAGACACCAAGGAACTGTGCATTTGGCGCATCG"
          + "GTCAGACCCAGTTTCGGCATCAGCAGAATCGCAACCAGCGTCAGCCAGAAAGAACCGTAAGAGGTGAATGCGGTTAAACC"
          + "GAAAGTGTTGCCTTTTTTGTACTCCAGCAGACCAGCAAAAATTTGCGCGATGCCGCCGTAGAAAATGCCCATGGCAAGAAT\n\n";

  private static FastaFiles instance = null;

  public static synchronized FastaFiles getInstance() {
    if (instance == null) {
      instance = new FastaFiles();
    }
    return instance;
  }

  /**
   * Get sequences for fasta files
   * 
   * @param count
   * @return String
   */
  public String getSequences(int count) { 
    StringBuilder sb = new StringBuilder();
    sb.append(FASTA_FILE_1);
    switch (count) { 
      case 1:
        break;
      case 2:
        sb.append(FASTA_FILE_2);
        break;
      case 3:
        sb.append(FASTA_FILE_2);
        sb.append(FASTA_FILE_3);
        break;
      case 4:
        sb.append(FASTA_FILE_2);
        sb.append(FASTA_FILE_3);
        sb.append(FASTA_FILE_4);
        break;
      case 5:
        sb.append(FASTA_FILE_2);
        sb.append(FASTA_FILE_3);
        sb.append(FASTA_FILE_4);
        sb.append(FASTA_FILE_5);
        break;
      case 6:
        sb.append(FASTA_FILE_2);
        sb.append(FASTA_FILE_3);
        sb.append(FASTA_FILE_4);
        sb.append(FASTA_FILE_5);
        sb.append(FASTA_FILE_6);
        break;
      default:
        return null;
    }
    return sb.toString();
  }
}
